title: Explore Azure 
author: exploreazure
email: barry@exploreazure.co.uk
theme: minima
description: > # this means to ignore newlines until "baseurl:"
This is a test using learning lab
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
